2022-05-11_13-37-58 [HikariPool-6 connection adder] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-6 - Error thrown while acquiring connection from data source
org.h2.jdbc.JdbcSQLNonTransientConnectionException: The database is open in exclusive mode; can not open additional connections [90135-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.engine.Session.checkSuspended(Session.java:1369)
	at org.h2.engine.Session.isOpen(Session.java:1303)
	at org.h2.engine.Session.waitIfExclusiveModeEnabled(Session.java:1639)
	at org.h2.command.Command.executeQuery(Command.java:186)
	at org.h2.jdbc.JdbcConnection.isReadOnly(JdbcConnection.java:631)
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:402)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:363)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2022-05-11_15-06-02 [http-nio-8102-exec-1] ERROR c.c.p.d.e.GlobalExceptionHandler - Aadhar Card Number is not Valid. Please check it and try again
2022-05-11_18-24-43 [http-nio-8102-exec-2] ERROR c.c.p.d.e.GlobalExceptionHandler - Not allowed
2022-05-11_18-24-43 [http-nio-8102-exec-2] ERROR c.c.p.d.e.GlobalExceptionHandler - Not allowed
2022-05-11_18-24-43 [http-nio-8102-exec-4] ERROR c.c.p.d.e.GlobalExceptionHandler - Not allowed
2022-05-11_18-24-43 [http-nio-8102-exec-5] ERROR c.c.p.d.e.GlobalExceptionHandler - Not allowed
2022-05-11_19-59-31 [http-nio-8102-exec-4] ERROR c.c.p.d.e.GlobalExceptionHandler - Not allowed
2022-05-11_19-59-31 [http-nio-8102-exec-5] ERROR c.c.p.d.e.GlobalExceptionHandler - Not allowed
2022-05-11_19-59-31 [http-nio-8102-exec-6] ERROR c.c.p.d.e.GlobalExceptionHandler - Not allowed
2022-05-11_19-59-31 [http-nio-8102-exec-7] ERROR c.c.p.d.e.GlobalExceptionHandler - Not allowed
2022-05-11_19-59-31 [http-nio-8102-exec-9] ERROR c.c.p.d.e.GlobalExceptionHandler - Not allowed
2022-05-11_19-59-31 [http-nio-8102-exec-3] ERROR c.c.p.d.e.GlobalExceptionHandler - Not allowed
2022-05-11_19-59-31 [http-nio-8102-exec-8] ERROR c.c.p.d.e.GlobalExceptionHandler - Not allowed
2022-05-11_19-59-31 [http-nio-8102-exec-10] ERROR c.c.p.d.e.GlobalExceptionHandler - Not allowed
2022-05-11_19-59-31 [http-nio-8102-exec-4] ERROR c.c.p.d.e.GlobalExceptionHandler - Not allowed
